import type { NodeDefinition } from '../../types/graph'

const SIDES = ['front', 'back', 'left', 'right', 'top', 'bottom']
const TURTLE_DIRECTIONS = ['Forward', 'Up', 'Down']
const NOTE_INSTRUMENTS = [
  'harp', 'bass', 'basedrum', 'snare', 'hat', 'bell', 'flute', 'chime', 'guitar', 'xylophone', 'pling',
]

function textProp(defaultValue: string) {
  return { Type: 'text' as const, DefaultValue: defaultValue, Options: [] }
}
function numberProp(defaultValue: string) {
  return { Type: 'number' as const, DefaultValue: defaultValue, Options: [] }
}
function comboProp(defaultValue: string, options: string[]) {
  return { Type: 'combo' as const, DefaultValue: defaultValue, Options: options }
}

/** CC:Tweaked node catalog — hand-authored from CC:Tweaked's own public Lua
 * API documentation (see ../../../docs/cc-tweaked-api-notes.md for sources),
 * not reused from any third-party tool. Original content, so a plain
 * TypeScript array rather than a JSON asset (same posture as Stationeers
 * IC10's catalog).
 *
 * Scoped for non-engineers building real automation, not as a minimal
 * proof-of-concept: unlike IC10 (hard 128-line/90-char cap that keeps any
 * catalog's practical reach small regardless of size), CC:Tweaked has no such
 * limit, so this catalog aims to cover the turtle/computer/peripheral surface
 * a builder would actually reach for — streamlined (one node per distinct
 * capability, a Direction/Side combo instead of duplicate per-direction
 * nodes) rather than either bloated or thin. "Custom Code" exists as a last
 * resort for the rare case nothing here covers, not as a substitute for a
 * dedicated node. */
export const nodeDefinitions: NodeDefinition[] = [
  // ── Control ──────────────────────────────────────────────────────────
  {
    Id: 'cct.start',
    Category: '🚀 Control',
    Title: 'Start',
    Description: 'Program entry point — where the computer/turtle begins running.',
    Search: 'start begin entry',
    ActionType: 'Start',
    InputPorts: [],
    OutputPorts: ['Next'],
    Properties: {},
    Preview: 'Start',
  },
  {
    Id: 'cct.wait_seconds',
    Category: '🚀 Control',
    Title: 'Wait Seconds',
    Description: 'Pauses for the given number of seconds before continuing.',
    Search: 'wait sleep pause delay',
    ActionType: 'WaitSeconds',
    InputPorts: ['In'],
    OutputPorts: ['Next'],
    Properties: { Seconds: numberProp('1') },
    Preview: 'Wait {Seconds}s',
  },
  {
    Id: 'cct.loop_to_start',
    Category: '🚀 Control',
    Title: 'Loop To Start',
    Description: 'Goes back to the Start node, forever — put this at the end of a branch you want to repeat.',
    Search: 'loop repeat restart forever goto',
    ActionType: 'LoopToStart',
    InputPorts: ['In'],
    OutputPorts: [],
    Properties: {},
    Preview: 'Loop to Start',
  },
  {
    Id: 'cct.print',
    Category: '🚀 Control',
    Title: 'Print',
    Description: 'Prints a line of text to the computer\'s own screen (not a monitor peripheral — see Write To Monitor for that).',
    Search: 'print write text log console',
    ActionType: 'Print',
    InputPorts: ['In'],
    OutputPorts: ['Next'],
    Properties: { Text: textProp('Hello, world!') },
    Preview: 'print {Text}',
  },
  {
    Id: 'cct.custom_code',
    Category: '🚀 Control',
    Title: 'Custom Code',
    Description: 'Drops in raw Lua, verbatim, for the rare case nothing else in the catalog covers what you need. Falls through to Next afterward.',
    Search: 'custom code lua raw script advanced',
    ActionType: 'CustomCode',
    InputPorts: ['In'],
    OutputPorts: ['Next'],
    Properties: { Code: { Type: 'multiline', DefaultValue: '-- your Lua here', Options: [] } },
    Preview: 'Custom Code',
  },

  // ── Checks ───────────────────────────────────────────────────────────
  {
    Id: 'cct.compare',
    Category: '✅ Checks',
    Title: 'Compare Numbers',
    Description: 'Compares Value A to Value B and branches True or False.',
    Search: 'compare if equal less greater than branch number',
    ActionType: 'Compare',
    InputPorts: ['In'],
    OutputPorts: ['True', 'False'],
    Properties: {
      ValueA: textProp('0'),
      Operator: comboProp('==', ['==', '~=', '<', '<=', '>', '>=']),
      ValueB: textProp('0'),
    },
    Preview: '{ValueA} {Operator} {ValueB} ?',
  },
  {
    Id: 'cct.text_equals',
    Category: '✅ Checks',
    Title: 'Text Equals',
    Description: 'Branches True if two pieces of text are exactly equal, False otherwise.',
    Search: 'text string equals compare match branch',
    ActionType: 'TextEquals',
    InputPorts: ['In'],
    OutputPorts: ['True', 'False'],
    Properties: { ValueA: textProp(''), ValueB: textProp('') },
    Preview: '{ValueA} == {ValueB} ?',
  },

  // ── Variables ────────────────────────────────────────────────────────
  {
    Id: 'cct.var.set',
    Category: '🔢 Variables',
    Title: 'Set Variable',
    Description: 'Stores a value — a number, text, or another variable\'s name — into a named variable for later nodes to use.',
    Search: 'set variable assign value',
    ActionType: 'SetVariable',
    InputPorts: ['In'],
    OutputPorts: ['Next'],
    Properties: { Name: textProp('value'), Value: textProp('0') },
    Preview: '{Name} = {Value}',
  },
  {
    Id: 'cct.var.math',
    Category: '🔢 Variables',
    Title: 'Number Math',
    Description: 'Computes Value A (Operator) Value B and stores the result in a named variable.',
    Search: 'math add subtract multiply divide modulo min max round floor abs sqrt',
    ActionType: 'NumberMath',
    InputPorts: ['In'],
    OutputPorts: ['Next'],
    Properties: {
      Name: textProp('result'),
      ValueA: textProp('0'),
      Operator: comboProp(
        'Add',
        ['Add', 'Subtract', 'Multiply', 'Divide', 'Modulo', 'Min', 'Max', 'Round', 'Floor', 'Ceil', 'Abs', 'Sqrt', 'Power'],
      ),
      ValueB: textProp('0'),
    },
    Preview: '{Name} = {ValueA} {Operator} {ValueB}',
  },
  {
    Id: 'cct.var.join_text',
    Category: '🔢 Variables',
    Title: 'Join Text',
    Description: 'Joins two pieces of text (or variables) together and stores the result in a named variable.',
    Search: 'join text concatenate combine string',
    ActionType: 'JoinText',
    InputPorts: ['In'],
    OutputPorts: ['Next'],
    Properties: { Name: textProp('joined'), ValueA: textProp(''), ValueB: textProp('') },
    Preview: '{Name} = {ValueA} .. {ValueB}',
  },

  // ── Peripherals (generic) ───────────────────────────────────────────
  {
    Id: 'cct.peripheral.present',
    Category: '🔌 Peripherals',
    Title: 'Peripheral Present?',
    Description: 'Branches True if something is attached on the given side or network name, False if not.',
    Search: 'peripheral present attached connected check',
    ActionType: 'PeripheralPresent',
    InputPorts: ['In'],
    OutputPorts: ['True', 'False'],
    Properties: { Side: textProp('front') },
    Preview: 'peripheral present at {Side}?',
  },
  {
    Id: 'cct.peripheral.call',
    Category: '🔌 Peripherals',
    Title: 'Call Peripheral Method',
    Description: 'Calls any method by name on a peripheral (side or network name) with up to three arguments, optionally storing its first return value. The general-purpose fallback for peripherals that don\'t have a dedicated node.',
    Search: 'peripheral call method generic advanced',
    ActionType: 'PeripheralCall',
    InputPorts: ['In'],
    OutputPorts: ['Next'],
    Properties: {
      Side: textProp('front'),
      Method: textProp('getMetadata'),
      Arg1: textProp(''),
      Arg2: textProp(''),
      Arg3: textProp(''),
      Name: textProp('(none)'),
    },
    Preview: '{Name} = {Side}.{Method}(...)',
  },

  // ── Redstone ─────────────────────────────────────────────────────────
  {
    Id: 'cct.redstone.read_digital',
    Category: '⚡ Redstone',
    Title: 'Read Digital Input',
    Description: 'Reads whether a redstone signal is present on a side (on/off) into a named variable.',
    Search: 'redstone read digital input side on off',
    ActionType: 'ReadDigitalInput',
    InputPorts: ['In'],
    OutputPorts: ['Next'],
    Properties: { Side: comboProp('front', SIDES), Name: textProp('signal') },
    Preview: '{Name} = redstone {Side} (digital)',
  },
  {
    Id: 'cct.redstone.write_digital',
    Category: '⚡ Redstone',
    Title: 'Write Digital Output',
    Description: 'Turns a redstone signal on a side on or off.',
    Search: 'redstone write digital output side on off',
    ActionType: 'WriteDigitalOutput',
    InputPorts: ['In'],
    OutputPorts: ['Next'],
    Properties: { Side: comboProp('front', SIDES), Value: comboProp('true', ['true', 'false']) },
    Preview: 'redstone {Side} (digital) = {Value}',
  },
  {
    Id: 'cct.redstone.read_analog',
    Category: '⚡ Redstone',
    Title: 'Read Analog Input',
    Description: 'Reads a redstone signal strength (0-15) on a side into a named variable.',
    Search: 'redstone read analog input side strength bundled',
    ActionType: 'ReadAnalogInput',
    InputPorts: ['In'],
    OutputPorts: ['Next'],
    Properties: { Side: comboProp('front', SIDES), Name: textProp('strength') },
    Preview: '{Name} = redstone {Side} (analog)',
  },
  {
    Id: 'cct.redstone.write_analog',
    Category: '⚡ Redstone',
    Title: 'Write Analog Output',
    Description: 'Sets a redstone signal strength (0-15) on a side.',
    Search: 'redstone write analog output side strength',
    ActionType: 'WriteAnalogOutput',
    InputPorts: ['In'],
    OutputPorts: ['Next'],
    Properties: { Side: comboProp('front', SIDES), Value: numberProp('15') },
    Preview: 'redstone {Side} (analog) = {Value}',
  },

  // ── Rednet ───────────────────────────────────────────────────────────
  {
    Id: 'cct.rednet.open',
    Category: '📡 Rednet',
    Title: 'Open Modem',
    Description: 'Opens a wireless/wired modem (by side) for rednet messaging — do this once before Send/Receive/Broadcast.',
    Search: 'rednet open modem wireless wired',
    ActionType: 'RednetOpen',
    InputPorts: ['In'],
    OutputPorts: ['Next'],
    Properties: { Side: comboProp('top', SIDES) },
    Preview: 'rednet.open({Side})',
  },
  {
    Id: 'cct.rednet.host',
    Category: '📡 Rednet',
    Title: 'Host Protocol',
    Description: 'Registers this computer under a protocol and hostname so other computers can find it by name instead of by numeric id.',
    Search: 'rednet host protocol hostname lookup name',
    ActionType: 'RednetHost',
    InputPorts: ['In'],
    OutputPorts: ['Next'],
    Properties: { Protocol: textProp('wirerig'), Hostname: textProp('my_computer') },
    Preview: 'rednet.host({Protocol}, {Hostname})',
  },
  {
    Id: 'cct.rednet.send',
    Category: '📡 Rednet',
    Title: 'Send Message',
    Description: 'Sends a message to one computer, addressed by its numeric id or hostname.',
    Search: 'rednet send message computer id hostname',
    ActionType: 'RednetSend',
    InputPorts: ['In'],
    OutputPorts: ['Next'],
    Properties: { Recipient: textProp(''), Message: textProp(''), Protocol: textProp('wirerig') },
    Preview: 'rednet.send({Recipient}, {Message})',
  },
  {
    Id: 'cct.rednet.broadcast',
    Category: '📡 Rednet',
    Title: 'Broadcast Message',
    Description: 'Sends a message to every computer listening on a protocol.',
    Search: 'rednet broadcast message all protocol',
    ActionType: 'RednetBroadcast',
    InputPorts: ['In'],
    OutputPorts: ['Next'],
    Properties: { Message: textProp(''), Protocol: textProp('wirerig') },
    Preview: 'rednet.broadcast({Message})',
  },
  {
    Id: 'cct.rednet.receive',
    Category: '📡 Rednet',
    Title: 'Receive Message',
    Description: 'Waits (up to Timeout seconds, or forever if 0) for a message, storing the message text and sender id into named variables. Branches Received/TimedOut.',
    Search: 'rednet receive message wait listen timeout',
    ActionType: 'RednetReceive',
    InputPorts: ['In'],
    OutputPorts: ['Received', 'TimedOut'],
    Properties: {
      Protocol: textProp('wirerig'),
      Timeout: numberProp('0'),
      NameMessage: textProp('message'),
      NameSender: textProp('senderId'),
    },
    Preview: '{NameMessage}, {NameSender} = rednet.receive({Protocol})',
  },

  // ── Turtle: Movement ─────────────────────────────────────────────────
  {
    Id: 'cct.turtle.move_forward',
    Category: '🐢 Turtle Movement',
    Title: 'Move Forward',
    Description: 'Moves the turtle one block forward. Branches Moved/Blocked.',
    Search: 'turtle move forward walk',
    ActionType: 'TurtleMoveForward',
    InputPorts: ['In'],
    OutputPorts: ['Moved', 'Blocked'],
    Properties: {},
    Preview: 'turtle.forward()',
  },
  {
    Id: 'cct.turtle.move_back',
    Category: '🐢 Turtle Movement',
    Title: 'Move Back',
    Description: 'Moves the turtle one block backward (without turning around). Branches Moved/Blocked.',
    Search: 'turtle move back backward retreat',
    ActionType: 'TurtleMoveBack',
    InputPorts: ['In'],
    OutputPorts: ['Moved', 'Blocked'],
    Properties: {},
    Preview: 'turtle.back()',
  },
  {
    Id: 'cct.turtle.move_up',
    Category: '🐢 Turtle Movement',
    Title: 'Move Up',
    Description: 'Moves the turtle one block up. Branches Moved/Blocked.',
    Search: 'turtle move up climb',
    ActionType: 'TurtleMoveUp',
    InputPorts: ['In'],
    OutputPorts: ['Moved', 'Blocked'],
    Properties: {},
    Preview: 'turtle.up()',
  },
  {
    Id: 'cct.turtle.move_down',
    Category: '🐢 Turtle Movement',
    Title: 'Move Down',
    Description: 'Moves the turtle one block down. Branches Moved/Blocked.',
    Search: 'turtle move down descend',
    ActionType: 'TurtleMoveDown',
    InputPorts: ['In'],
    OutputPorts: ['Moved', 'Blocked'],
    Properties: {},
    Preview: 'turtle.down()',
  },
  {
    Id: 'cct.turtle.turn_left',
    Category: '🐢 Turtle Movement',
    Title: 'Turn Left',
    Description: 'Turns the turtle 90° left.',
    Search: 'turtle turn left rotate',
    ActionType: 'TurtleTurnLeft',
    InputPorts: ['In'],
    OutputPorts: ['Next'],
    Properties: {},
    Preview: 'turtle.turnLeft()',
  },
  {
    Id: 'cct.turtle.turn_right',
    Category: '🐢 Turtle Movement',
    Title: 'Turn Right',
    Description: 'Turns the turtle 90° right.',
    Search: 'turtle turn right rotate',
    ActionType: 'TurtleTurnRight',
    InputPorts: ['In'],
    OutputPorts: ['Next'],
    Properties: {},
    Preview: 'turtle.turnRight()',
  },

  // ── Turtle: World ────────────────────────────────────────────────────
  {
    Id: 'cct.turtle.dig',
    Category: '🐢 Turtle World',
    Title: 'Dig',
    Description: 'Breaks the block in front of, above, or below the turtle. Branches Dug/Empty (nothing there to dig).',
    Search: 'turtle dig mine break forward up down',
    ActionType: 'TurtleDig',
    InputPorts: ['In'],
    OutputPorts: ['Dug', 'Empty'],
    Properties: { Direction: comboProp('Forward', TURTLE_DIRECTIONS) },
    Preview: 'turtle.dig({Direction})',
  },
  {
    Id: 'cct.turtle.place',
    Category: '🐢 Turtle World',
    Title: 'Place',
    Description: 'Places the item from the currently selected slot in front of, above, or below the turtle. Branches Placed/Failed.',
    Search: 'turtle place put block item forward up down',
    ActionType: 'TurtlePlace',
    InputPorts: ['In'],
    OutputPorts: ['Placed', 'Failed'],
    Properties: { Direction: comboProp('Forward', TURTLE_DIRECTIONS) },
    Preview: 'turtle.place({Direction})',
  },
  {
    Id: 'cct.turtle.detect',
    Category: '🐢 Turtle World',
    Title: 'Detect',
    Description: 'Checks whether there\'s a solid block in front of, above, or below the turtle. Branches True/False.',
    Search: 'turtle detect check block solid forward up down',
    ActionType: 'TurtleDetect',
    InputPorts: ['In'],
    OutputPorts: ['True', 'False'],
    Properties: { Direction: comboProp('Forward', TURTLE_DIRECTIONS) },
    Preview: 'turtle.detect({Direction})',
  },
  {
    Id: 'cct.turtle.inspect',
    Category: '🐢 Turtle World',
    Title: 'Inspect',
    Description: 'Looks at the block in front of, above, or below the turtle and stores its name into a variable. Branches Found/Empty.',
    Search: 'turtle inspect look block name identify forward up down',
    ActionType: 'TurtleInspect',
    InputPorts: ['In'],
    OutputPorts: ['Found', 'Empty'],
    Properties: { Direction: comboProp('Forward', TURTLE_DIRECTIONS), Name: textProp('blockName') },
    Preview: '{Name} = turtle.inspect({Direction})',
  },

  // ── Turtle: Inventory ────────────────────────────────────────────────
  {
    Id: 'cct.turtle.select_slot',
    Category: '🐢 Turtle Inventory',
    Title: 'Select Slot',
    Description: 'Selects an inventory slot (1-16) as the turtle\'s active slot for future actions.',
    Search: 'turtle select slot inventory active',
    ActionType: 'TurtleSelectSlot',
    InputPorts: ['In'],
    OutputPorts: ['Next'],
    Properties: { Slot: numberProp('1') },
    Preview: 'turtle.select({Slot})',
  },
  {
    Id: 'cct.turtle.get_item_count',
    Category: '🐢 Turtle Inventory',
    Title: 'Get Item Count',
    Description: 'Stores how many items are in a slot (1-16) into a named variable.',
    Search: 'turtle item count slot inventory how many',
    ActionType: 'GetItemCount',
    InputPorts: ['In'],
    OutputPorts: ['Next'],
    Properties: { Slot: numberProp('1'), Name: textProp('count') },
    Preview: '{Name} = turtle.getItemCount({Slot})',
  },
  {
    Id: 'cct.turtle.get_item_detail',
    Category: '🐢 Turtle Inventory',
    Title: 'Get Item Detail',
    Description: 'Stores the item name in a slot (1-16) into a named variable, or an empty string if the slot is empty.',
    Search: 'turtle item detail slot inventory name what',
    ActionType: 'GetItemDetail',
    InputPorts: ['In'],
    OutputPorts: ['Next'],
    Properties: { Slot: numberProp('1'), Name: textProp('itemName') },
    Preview: '{Name} = turtle.getItemDetail({Slot})',
  },
  {
    Id: 'cct.turtle.suck',
    Category: '🐢 Turtle Inventory',
    Title: 'Suck',
    Description: 'Picks up items from in front of, above, or below the turtle (an inventory or the ground). Branches Sucked/Empty.',
    Search: 'turtle suck pick up items collect forward up down',
    ActionType: 'TurtleSuck',
    InputPorts: ['In'],
    OutputPorts: ['Sucked', 'Empty'],
    Properties: { Direction: comboProp('Forward', TURTLE_DIRECTIONS) },
    Preview: 'turtle.suck({Direction})',
  },
  {
    Id: 'cct.turtle.drop',
    Category: '🐢 Turtle Inventory',
    Title: 'Drop',
    Description: 'Drops items from the selected slot in front of, above, or below the turtle. Branches Dropped/Failed.',
    Search: 'turtle drop items give forward up down',
    ActionType: 'TurtleDrop',
    InputPorts: ['In'],
    OutputPorts: ['Dropped', 'Failed'],
    Properties: { Direction: comboProp('Forward', TURTLE_DIRECTIONS), Count: numberProp('0') },
    Preview: 'turtle.drop({Direction}, {Count})',
  },
  {
    Id: 'cct.turtle.refuel',
    Category: '🐢 Turtle Inventory',
    Title: 'Refuel',
    Description: 'Consumes fuel items from the selected slot. Branches Refueled/NoFuel.',
    Search: 'turtle refuel fuel coal energy',
    ActionType: 'TurtleRefuel',
    InputPorts: ['In'],
    OutputPorts: ['Refueled', 'NoFuel'],
    Properties: { Count: numberProp('0') },
    Preview: 'turtle.refuel({Count})',
  },

  // ── Turtle: Navigation ───────────────────────────────────────────────
  {
    Id: 'cct.turtle.gps_locate',
    Category: '🐢 Turtle Navigation',
    Title: 'Get GPS Position',
    Description: 'Asks nearby GPS host computers for this turtle\'s world position, storing X/Y/Z into named variables. Requires GPS hosts to be set up in the world.',
    Search: 'gps locate position location coordinates xyz',
    ActionType: 'GetGpsPosition',
    InputPorts: ['In'],
    OutputPorts: ['Found', 'NotFound'],
    Properties: { NameX: textProp('posX'), NameY: textProp('posY'), NameZ: textProp('posZ') },
    Preview: '{NameX},{NameY},{NameZ} = gps.locate()',
  },
  {
    Id: 'cct.turtle.get_fuel_level',
    Category: '🐢 Turtle Navigation',
    Title: 'Get Fuel Level',
    Description: 'Stores the turtle\'s current fuel level into a named variable.',
    Search: 'turtle fuel level remaining check',
    ActionType: 'GetFuelLevel',
    InputPorts: ['In'],
    OutputPorts: ['Next'],
    Properties: { Name: textProp('fuel') },
    Preview: '{Name} = turtle.getFuelLevel()',
  },

  // ── Monitor ──────────────────────────────────────────────────────────
  {
    Id: 'cct.monitor.clear',
    Category: '🖥 Monitor',
    Title: 'Clear Monitor',
    Description: 'Clears everything drawn on a monitor peripheral (side or network name).',
    Search: 'monitor clear screen wipe',
    ActionType: 'ClearMonitor',
    InputPorts: ['In'],
    OutputPorts: ['Next'],
    Properties: { Side: textProp('top') },
    Preview: '{Side}.clear()',
  },
  {
    Id: 'cct.monitor.write',
    Category: '🖥 Monitor',
    Title: 'Write To Monitor',
    Description: 'Writes text to a monitor peripheral at a given column/row.',
    Search: 'monitor write text display screen',
    ActionType: 'WriteToMonitor',
    InputPorts: ['In'],
    OutputPorts: ['Next'],
    Properties: { Side: textProp('top'), Column: numberProp('1'), Row: numberProp('1'), Text: textProp('Hello!') },
    Preview: '{Side}: write {Text} at {Column},{Row}',
  },
  {
    Id: 'cct.monitor.set_scale',
    Category: '🖥 Monitor',
    Title: 'Set Monitor Text Scale',
    Description: 'Sets a monitor\'s text scale (0.5-5).',
    Search: 'monitor text scale size zoom',
    ActionType: 'SetMonitorScale',
    InputPorts: ['In'],
    OutputPorts: ['Next'],
    Properties: { Side: textProp('top'), Scale: numberProp('1') },
    Preview: '{Side}.setTextScale({Scale})',
  },
  {
    Id: 'cct.monitor.set_colors',
    Category: '🖥 Monitor',
    Title: 'Set Monitor Colors',
    Description: 'Sets a monitor\'s background and text colors.',
    Search: 'monitor color background text',
    ActionType: 'SetMonitorColors',
    InputPorts: ['In'],
    OutputPorts: ['Next'],
    Properties: {
      Side: textProp('top'),
      Background: comboProp('black', ['white', 'orange', 'magenta', 'lightBlue', 'yellow', 'lime', 'pink', 'gray', 'lightGray', 'cyan', 'purple', 'blue', 'brown', 'green', 'red', 'black']),
      Text: comboProp('white', ['white', 'orange', 'magenta', 'lightBlue', 'yellow', 'lime', 'pink', 'gray', 'lightGray', 'cyan', 'purple', 'blue', 'brown', 'green', 'red', 'black']),
    },
    Preview: '{Side}: colors {Background}/{Text}',
  },

  // ── Speaker ──────────────────────────────────────────────────────────
  {
    Id: 'cct.speaker.play_note',
    Category: '🔊 Speaker',
    Title: 'Play Note',
    Description: 'Plays a single instrument note on a speaker peripheral.',
    Search: 'speaker play note sound instrument music',
    ActionType: 'PlayNote',
    InputPorts: ['In'],
    OutputPorts: ['Next'],
    Properties: {
      Side: textProp('right'),
      Instrument: comboProp('harp', NOTE_INSTRUMENTS),
      Pitch: numberProp('12'),
      Volume: numberProp('1'),
    },
    Preview: '{Side}.playNote({Instrument})',
  },
  {
    Id: 'cct.speaker.play_sound',
    Category: '🔊 Speaker',
    Title: 'Play Sound',
    Description: 'Plays a named sound effect on a speaker peripheral (e.g. "minecraft:entity.experience_orb.pickup").',
    Search: 'speaker play sound effect audio',
    ActionType: 'PlaySound',
    InputPorts: ['In'],
    OutputPorts: ['Next'],
    Properties: { Side: textProp('right'), Sound: textProp('minecraft:entity.experience_orb.pickup'), Volume: numberProp('1') },
    Preview: '{Side}.playSound({Sound})',
  },

  // ── Disk Drive ───────────────────────────────────────────────────────
  {
    Id: 'cct.disk.is_present',
    Category: '💾 Disk Drive',
    Title: 'Is Disk Present?',
    Description: 'Branches True if a floppy disk/item is in the disk drive, False if not.',
    Search: 'disk drive present floppy check',
    ActionType: 'IsDiskPresent',
    InputPorts: ['In'],
    OutputPorts: ['True', 'False'],
    Properties: { Side: textProp('left') },
    Preview: '{Side}.isDiskPresent()',
  },
  {
    Id: 'cct.disk.eject',
    Category: '💾 Disk Drive',
    Title: 'Eject Disk',
    Description: 'Ejects whatever disk/item is currently in the disk drive.',
    Search: 'disk drive eject remove floppy',
    ActionType: 'EjectDisk',
    InputPorts: ['In'],
    OutputPorts: ['Next'],
    Properties: { Side: textProp('left') },
    Preview: '{Side}.ejectDisk()',
  },
]
