import { describe, expect, it } from 'vitest'
import type { NodeConnection, ScriptNode } from '../../../types/graph'
import { generateScript } from './generate'
import { nodeDefinitions } from '../nodeLibrary'
import { advancedPeripheralsAddon } from '../advancedPeripherals'

let counter = 0
function node(partial: Partial<ScriptNode> & Pick<ScriptNode, 'ActionType'>): ScriptNode {
  counter += 1
  return {
    Id: partial.Id ?? `nid${counter}`,
    Number: partial.Number ?? counter,
    DefinitionId: partial.DefinitionId ?? partial.ActionType,
    ActionType: partial.ActionType,
    Title: partial.Title ?? partial.ActionType,
    Description: partial.Description ?? '',
    X: 0,
    Y: 0,
    InputPorts: partial.InputPorts ?? ['In'],
    OutputPorts: partial.OutputPorts ?? ['Next'],
    Properties: partial.Properties ?? {},
  }
}

function wire(from: ScriptNode, fromPort: string, to: ScriptNode, toPort = 'In'): NodeConnection {
  return { FromNodeId: from.Id, FromPort: fromPort, ToNodeId: to.Id, ToPort: toPort }
}

describe('generateScript', () => {
  it('reports missing Start node', () => {
    const { source, warnings } = generateScript([], [])
    expect(source).toContain('No Start node')
    expect(warnings).toEqual([])
  })

  it('an unconnected Start loops back to itself via a Lua tail call', () => {
    const start = node({ ActionType: 'Start' })
    const { source, warnings } = generateScript([start], [])
    expect(warnings).toEqual([])
    expect(source).toBe(
      [
        '-- Generated by WireRig',
        `local step${start.Number}`,
        `step${start.Number} = function()`,
        `  return step${start.Number}()`,
        'end',
        `step${start.Number}()`,
      ].join('\n'),
    )
  })

  it('chains Start -> Print, falling through to an unconnected Next (loop to start)', () => {
    const start = node({ ActionType: 'Start' })
    const print = node({ ActionType: 'Print', Properties: { Text: 'Hello!' } })
    const nodes = [start, print]
    const connections = [wire(start, 'Next', print)]

    const { source, warnings } = generateScript(nodes, connections)
    expect(warnings).toEqual([])
    expect(source).toBe(
      [
        '-- Generated by WireRig',
        `local step${start.Number}, step${print.Number}`,
        `step${start.Number} = function()`,
        `  return step${print.Number}()`,
        'end',
        `step${print.Number} = function()`,
        '  print("Hello!")',
        `  return step${start.Number}()`,
        'end',
        `step${start.Number}()`,
      ].join('\n'),
    )
  })

  it('declares variables once, up front, shared across step functions', () => {
    const start = node({ ActionType: 'Start' })
    const setVar = node({ ActionType: 'SetVariable', Properties: { Name: 'counter', Value: '0' } })
    const nodes = [start, setVar]
    const connections = [wire(start, 'Next', setVar)]

    const { source } = generateScript(nodes, connections)
    expect(source).toContain(`local counter\nlocal step${start.Number}, step${setVar.Number}`)
    expect(source).toContain('counter = 0')
  })

  it('warns and skips declaring an invalid Lua variable name, but still generates', () => {
    const start = node({ ActionType: 'Start' })
    const setVar = node({ ActionType: 'SetVariable', Properties: { Name: 'not a name', Value: '0' } })
    const nodes = [start, setVar]
    const connections = [wire(start, 'Next', setVar)]

    const { warnings, source } = generateScript(nodes, connections)
    expect(warnings).toHaveLength(1)
    expect(warnings[0]).toContain('not a name')
    expect(source).toContain('invalid variable name')
  })

  it('Compare branches True/False as a tail-call if/else', () => {
    const start = node({ ActionType: 'Start' })
    const setVar = node({ ActionType: 'SetVariable', Properties: { Name: 'x', Value: '5' } })
    const compare = node({
      ActionType: 'Compare',
      OutputPorts: ['True', 'False'],
      Properties: { ValueA: 'x', Operator: '>', ValueB: '10' },
    })
    const onTrue = node({ ActionType: 'Print', Properties: { Text: 'big' } })
    const onFalse = node({ ActionType: 'Print', Properties: { Text: 'small' } })
    const nodes = [start, setVar, compare, onTrue, onFalse]
    const connections = [
      wire(start, 'Next', setVar),
      wire(setVar, 'Next', compare),
      wire(compare, 'True', onTrue),
      wire(compare, 'False', onFalse),
    ]

    const { source, warnings } = generateScript(nodes, connections)
    expect(warnings).toEqual([])
    expect(source).toContain('if x > 10 then')
    expect(source).toContain(`  return step${onTrue.Number}()`)
    expect(source).toContain(`  return step${onFalse.Number}()`)
  })

  it('a turtle move chain compiles to branch-and-tail-call, looping on Blocked', () => {
    const start = node({ ActionType: 'Start' })
    const forward = node({ ActionType: 'TurtleMoveForward', OutputPorts: ['Moved', 'Blocked'] })
    const dig = node({ ActionType: 'TurtleDig', OutputPorts: ['Dug', 'Empty'], Properties: { Direction: 'Forward' } })
    const nodes = [start, forward, dig]
    const connections = [
      wire(start, 'Next', forward),
      wire(forward, 'Moved', dig),
      wire(forward, 'Blocked', dig),
    ]

    const { source, warnings } = generateScript(nodes, connections)
    expect(warnings).toEqual([])
    expect(source).toContain('if turtle.forward() then')
    expect(source).toContain('if turtle.dig() then')
    // Both Dug/Empty fall through to the (unconnected) Start loop.
    expect(source).toContain(`  return step${start.Number}()`)
  })

  it('a peripheral call resolves a declared variable, a number, and quotes free text', () => {
    const start = node({ ActionType: 'Start' })
    const read = node({ ActionType: 'ReadDigitalInput', Properties: { Side: 'front', Name: 'signal' } })
    const call = node({
      ActionType: 'PeripheralCall',
      Properties: { Side: 'back', Method: 'getMetadata', Arg1: 'signal', Arg2: '5', Arg3: '', Name: '(none)' },
    })
    const nodes = [start, read, call]
    const connections = [wire(start, 'Next', read), wire(read, 'Next', call)]

    const { source, warnings } = generateScript(nodes, connections)
    expect(warnings).toEqual([])
    expect(source).toContain('signal = redstone.getInput("front")')
    expect(source).toContain('peripheral.call("back", "getMetadata", signal, 5)')
  })

  it('resolves a rednet receive into named sender/message variables and branches Received/TimedOut', () => {
    const start = node({ ActionType: 'Start' })
    const receive = node({
      ActionType: 'RednetReceive',
      OutputPorts: ['Received', 'TimedOut'],
      Properties: { Protocol: 'wirerig', Timeout: '5', NameMessage: 'msg', NameSender: 'sender' },
    })
    const onReceived = node({ ActionType: 'Print', Properties: { Text: 'got one' } })
    const onTimeout = node({ ActionType: 'Print', Properties: { Text: 'nothing' } })
    const nodes = [start, receive, onReceived, onTimeout]
    const connections = [
      wire(start, 'Next', receive),
      wire(receive, 'Received', onReceived),
      wire(receive, 'TimedOut', onTimeout),
    ]

    const { source, warnings } = generateScript(nodes, connections)
    expect(warnings).toEqual([])
    expect(source).toContain('local rnSender, rnMessage = rednet.receive("wirerig", 5 > 0 and 5 or nil)')
    expect(source).toContain('sender = rnSender')
    expect(source).toContain('msg = rnMessage')
    expect(source).toContain('if rnSender ~= nil then')
  })

  // Advanced Peripherals addon ActionTypes need no special handling — they
  // resolve through the exact same generator/emitter table as base nodes,
  // regardless of whether the palette toggle that surfaces them in the UI
  // is currently on (codegen doesn't know about the toggle at all).
  it('generates an Advanced Peripherals node (ME Bridge item count) like any other node', () => {
    const start = node({ ActionType: 'Start' })
    const meCount = node({
      ActionType: 'MeGetItemCount',
      Properties: { Side: 'back', Item: 'minecraft:iron_ingot', Name: 'ironCount' },
    })
    const nodes = [start, meCount]
    const connections = [wire(start, 'Next', meCount)]

    const { source, warnings } = generateScript(nodes, connections)
    expect(warnings).toEqual([])
    expect(source).toContain('ironCount = peripheral.call("back", "getItemCount", "minecraft:iron_ingot")')
  })

  it('every catalog node (base + Advanced Peripherals) has real codegen, not the TODO stub', () => {
    const allDefs = [...nodeDefinitions, ...advancedPeripheralsAddon.nodeDefinitions]
    for (const def of allDefs) {
      if (def.ActionType === 'Start') continue
      const start = node({ ActionType: 'Start' })
      const target = node({
        ActionType: def.ActionType,
        OutputPorts: def.OutputPorts,
        Properties: Object.fromEntries(Object.entries(def.Properties).map(([k, v]) => [k, v.DefaultValue])),
      })
      const { source } = generateScript([start, target], [wire(start, 'Next', target)])
      expect(source, `${def.ActionType} ("${def.Title}") fell through to the TODO stub`).not.toContain('TODO codegen')
    }
  })

  it('includes a professional-comments header when requested', () => {
    const start = node({ ActionType: 'Start', Title: 'Start' })
    const { source } = generateScript([start], [], { professionalComments: true })
    expect(source).toContain(`-- #${start.Number} Start`)
  })
})
